---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(comment = '>')
```

### CS5706
###  Lab 04 - Exploratory Data Analysis in R
#### Exercise: EDA and PCA
*Alessandro Pandini*
Revision: 1.01

***

#### 1. load data and summary statistics
```{r}
### 1.1 load the data from the heptatlon.csv file and inspect it
###   the dataset is available also in the HSAUR package


df <- read.csv("heptatlon.csv", na.strings = c("NA", ""))


### 1.2 get a summary report of the variables

summary(df)

### 1.3 remove the score variable from the dataset

df_clean <- df[, -c(8)]
df_clean

### 1.4 calculate pearson correlation coefficient for the dataset
cor(df_clean)
```

#### 2. graphical analysis
```{r}
### 2.1 create a vector s_variables of labels for:
###   hurdles, run200m, run800m

s_variables <- c(df_clean$hurdles, df_clean$run200m, df_clean$run800m)

### 2.2 create a vector m_variables of labels for:
###   highjump, longjump, javelin

m_variables <- c(df_clean$highjump, df_clean$longjump, df_clean$javelin)


### 2.3 generate three simple boxplots for s_variables, m_variables and shot
###   display all three plots on one page

boxplot(s_variables)
boxplot(m_variables)
boxplot(df_clean$shot)

```

#### 3. PCA
```{r}
### 3.1 perform PCA on the dataset (without the score variable)

pc_df <- prcomp(df_clean, center = T, scale. = T)

```

#### 4. Visual analysis of PCA results
```{r}
### 4.1 calculate the proportion of exaplained variance (PEV) from the std values

pc_df_var <- pc_df$sdev^2
pc_df_pev <- pc_df_var / sum(pc_df_var)
pc_df_pev

plot(pc_df)

### 4.2 plot the cumulative PEV

opar <- par(no.readonly = TRUE)
plot(
  cumsum(pc_df_pev),
  ylim = c(0,1),
  xlab = 'PC',
  ylab = 'cumulative PEV',
  pch = 20,
  col = 'orange'
)
abline(h = 0.8, col = 'red', lty = 'dashed')
par(opar)


### 4.3 get and inspect the loadings

pc_df_loadings <- pc_df$rotation
pc_df_loadings

opar <- par(no.readonly = TRUE)
colvector = c('red', 'orange', 'yellow', 'green', 'cyan', 'blue', 'brown')
labvector = c('PC1', 'PC2', 'PC3')
barplot(
  pc_df_loadings[,c(1:3)],
  beside = T,
  yaxt = 'n',
  names.arg = labvector,
  col = colvector,
  ylim = c(-1,1),
  border = 'white',
  ylab = 'loadings'
)
axis(2, seq(-1,1,0.1))
legend(
  'bottomright',
  bty = 'n',
  col = colvector,
  pch = 15,
  row.names(pc_df_loadings)
)
par(opar)

### 4.4 generate a biplot for PC1 and PC2

opar <- par(no.readonly = TRUE)
par(mfrow = c(2,2))
biplot(
  pc_df,
  scale = 0,
  col = c('grey40','orange')
)
par(opar)

```
