---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(comment = '>')
```

### CS5706
### Lab 02 - Introduction to R for ML
#### Exercise: linear regression
*Alessandro Pandini*  
Revision: 1.01

***

```{r}
# load external functions
source('CS5706_Lab_02_Functions.R')
```

#### 0. load required packages
```{r}
library(psych)
```

#### 1. load data
```{r}
### 1.1 load the data from the chickendeef.csv data set

df <- read.csv("chickenfeed.csv", stringsAsFactors = FALSE)


### 1.2 create a cf_linseed dataset filtered for linseed feed

cf_linseed <- df[df$Feed == "linseed", ]

### 1.3 create a cf_linseed_data dataset filtered for Chick < 36

cf_linseed_data <- cf_linseed[cf_linseed$Chick <36, ]


### 1.4 create a cf_linseed_test dataset filtered for Chick >= 36

cf_linseed_test <- cf_linseed[cf_linseed$Chick >=36, ]


```

#### 2. data exploration
```{r}
### 2.1 save a scatterplots matrix for the cf_linseed_data
###     note: exclude the Feed variable

cf_num <- c("weight", "Time", "Chick")

pairs.panels(cf_linseed_data[cf_num])

#To save it we would run the followig:
#png(file = "scatterplot_matrix.png")
#pairs.panels(cf_linseed_data[cf_num])
#dev.off()

### 2.2 calculate a correlation matrix for the cf_linseed_data
###     note: exclude the Feed variable

cor_matrix <- cor(cf_linseed_data[cf_num])
cor(cf_linseed_data[cf_num])

### 2.3 save the correlation matrix in a csv file

#write.csv(cor_matrix, "cor_matrix.csv", row.names=FALSE)

```

#### 3. model training
```{r}
### 3.1 create a lm model cf_linseed_lm for weight over Time in cf_linseed_data

cf_linseed_lm <- lm(weight ~ Time, data = cf_linseed_data)

### 3.2 save the cf_linseed_lm object in a RData file

#save(cf_linseed_lm, file = "cf_linseed_lm.RData")

```

#### 4. model evaluation
```{r}
### 4.1 get summary statistics on the model

model_summary <- summary(cf_linseed_lm)
model_summary

### 4.2 save the model summary object in a RData file

#save(model_summary, file = "model_summary.RData")


### 4.3 save the coefficients table in a csv file

coef(model_summary)
#write.csv(coef(model_summary), "coef.csv", row.names=FALSE)

### 4.4 save the diagnostics plots for the lm model in a pdf file

plots <- plot(cf_linseed_lm)
plots

#pdf(file = "plots.pdf")
#plots
#dev.off()


```

#### 5. prediction
```{r}
### 5.1 run a prediction of weight for the cf_linseed_test using the cf_linseed_lm

indep_names <- c("Time", "Chick" )
test_indep <- cf_linseed_test[,indep_names]
pred <- predict(cf_linseed_lm, test_indep)

### 5.2 add a column pred with the predicted values to the cf_linseed_test table

cf_linseed_test$pred <- pred

### 5.3 save the updated cf_linseed_test table in a new csv file

#write.csv(cf_linseed_test_pred, "test_predictions.csv", row.names=FALSE)

### 5.4 save a predicted VS actual plot in a pdf file
###     note: use the plotPredAct function

plotPredAct(pred, cf_linseed_test$weight, "Predicted vs Actual", cf_linseed_test$weight, cf_linseed_test$Time)
#pdf(file = "predvsactual.pdf")
#plotPredAct
#dev.off()
```
